dist: xenial
sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

    # Running tests
    - sudo swapoff -a
    - sudo CTEST_OUTPUT_ON_FAILURE=true make test
